[project]
name = "salarycalc"
version = "2.0"
description = "Python scripts to update Salary Calc base values."
authors = [
    {name = "Niteo", email = "info@niteo.co"},
]
license = {text = "MIT"}
requires-python = ">=3.11"
keywords = [ "salaries"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "ruamel.yaml",
    "requests",
    "tqdm",
]

[dependency-groups]
dev = [
    "black",
    "codespell",
    "flake8",
    "flake8-assertive",
    "flake8-blind-except",
    "flake8-bugbear",
    "flake8-builtins",
    "flake8-comprehensions",
    "flake8-debugger",
    "flake8-deprecated",
    "flake8-docstrings",
    "flake8-isort",
    "flake8-mock",
    "flake8-mutable",
    "flake8-plone-hasattr",
    "flake8-self",
    "flake8-super-call",
    "flake8-todo",
    "flake8-tuple",
    "mypy",
    "pdbpp",
    "pre-commit-hooks",
    "pydocstyle<4.0.0",
    "yamllint",
]
