name: "Prepare nix-shell"
description:
  Download cache, build nix-shell and potentially upload any new
  derivations to cache

inputs:
  cachix_auth_token:
    required: true

runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: niteo-public
        authToken: '${{ inputs.cachix_auth_token }}'

    - name: Build nix-shell
      shell: bash
      run: nix-shell --run "echo 'nix-shell successfully entered'"
